### ISSUE TITLE
Bug: decompress function always throw an error.

### ISSUE THREAD

**Issue by yshing** [diamondrod/kdbplus#1]
The decompress function always throws the error `slice does not have length 4`.
https://github.com/diamondrod/kdbplus/blob/11967827e99f2ee421fb7fa7b8505a2c6575ebc5/kdbplus/src/ipc/connection.rs#L1135-L1136

Caused by the typo in the above 2 lines. `0..3` should be replaced by `0..=3` or `0..4`.

**Comment by diamondrod** [comment]
Thank you for the report and bug fix. What an elementary mistake... Anyway I will take your PR.
