### ISSUE TITLE
Group attribute value is 5, not 4.

### ISSUE THREAD

**Issue by cruzzil** [diamondrod/kdbplus#3]
https://github.com/diamondrod/kdbplus/blob/e5132f64a44908404f9c72be8c8180518271bf73/kdbplus/src/lib.rs#L143

**Comment by travis-leith** [comment]
@petesmc, do you know of any link to documentation or a link to another implementation that demonstrates this?
I have looked through a c# implementation for this and apparently it doesn't even cover attributes at all!

**Comment by cruzzil** [comment]
I haven’t found any documentation either but last time I checked I just set the attribute in KDB and then called a rust FFI and inspected the value for each different attribute.


________________________________

**Comment by travis-leith** [comment]
Here is an example that supports the observations by @petesmc 

https://github.com/Fifthrow/rust-kdb/blob/06ac2418a98fa1ad157156fef81c7e124d049d2d/src/k.rs#L113-L115

**Comment by diamondrod** [comment]
Hi, you can check that the group attribute is 4 by simply serializing a list with various attributes.
```q
q)-8!1 2i
0x010000001600000006**00**020000000100000002000000
q)-8!`s#1 2i
0x010000001600000006**01**020000000100000002000000
q)-8!`u#1 2i
0x010000001600000006**02**020000000100000002000000
q)-8!`p#1 2i
0x010000001600000006**03**020000000100000002000000
q)-8!`g#1 2i
0x010000001600000006**04**020000000100000002000000`
```
You can ignore header bytes. The `1 2i` is serialized in the following way
```text
type, attribute, length, (element)+
```
The version I am using is 4.0. If KX added a new attribute after this version, my implementation can  be out of date.

**Comment by travis-leith** [comment]
I have confirmed the serailzation results. @petesmc would be awesome if you could run your rust ffi test again.

EDIT:
hang on, did you run the test usin the rust lib I linked to above? If so, that lib might have an incorrect value which it was feeding to you.

**Comment by cruzzil** [comment]
Confirmed still seeing 5 when using FFI, but using kdb internal function see 4. Using kdb 4.0. 

Pseudo-ish code, sorry typing on mobile. If it prints only 8 bytes then means you are printing the pointer address instead of the contents. Might need to fix up references / de references. 

```rust
use kdbplus::api::*

#[no_mangle]
pub unsafe extern “C” fn pr(k: K) {
 println!(“{:x?}”, as_u8_slice(&*k))
}

unsafe fn as_u8_slice<T: Sized>(p: &T) -> &[u8] {
    core::slice::from_raw_parts(
        (p as *const T) as *const u8, 
        core::mem::size_of::<T>()
    )
}

```
