### ISSUE TITLE
Deserialization from a select query

### ISSUE THREAD

**Issue by kurudj** [diamondrod/kdbplus#9]
Hi!
Complete kdb noob here, as well as a Rust beginner. Trying to figure out if there is a way to properly deserialize the K type result from simple select statements into Rust structs. Would appreciate any guidance on a simplest example.
Thank you.

**Comment by diamondrod** [comment]
Hi,

The example in README not enough for you? You can use `send_sync_message`.

**Comment by kurudj** [comment]
Hi @diamondrod - I have checked all the examples and so far been relying on my own string parsing method for the query result. Hence, I’m wondering if there’s a built-in deserialization.

**Comment by diamondrod** [comment]
Hi, there is no conversion from `K` into Rust struct. Maybe you want serde-like deserialization from `Vec<u8>` or `[u8]` but it is not supported yet.

**Comment by kurudj** [comment]
Understood - thank you
